const SET_SCRABBLED_LETTERS = 'SET_SCRABBLED_LETTERS';
const ADD_LETTER_TO_GUESSED_WORD = 'ADD_LETTER_TO_GUESSED_WORD';
const REMOVE_LETTER_TO_GUESSED_WORD = 'REMOVE_LETTER_TO_GUESSED_WORD';

export {
    SET_SCRABBLED_LETTERS,
    ADD_LETTER_TO_GUESSED_WORD,
    REMOVE_LETTER_TO_GUESSED_WORD
}